"""Explain panel — SQL, rerank rationale, semantic objects, MetricFlow SQL, data health, lineage."""

import json
import streamlit as st
from typing import Dict, Any


_TAB_HELP = {
    "metricflow_sql": (
        "The SQL generated by dbt MetricFlow from the Semantic Layer. "
        "This query is compiled from governed metric and dimension "
        "definitions — not hand-written — ensuring consistent, auditable results."
    ),
    "candidate_sql_order": (
        "The deterministic SQL query run directly against Snowflake to "
        "retrieve candidate orders matching the search criteria. "
        "This step does not use the Semantic Layer."
    ),
    "candidate_sql_metric": (
        "For metric queries the SQL is generated by dbt MetricFlow "
        "through the Semantic Layer (shown in the MetricFlow SQL tab). "
        "This tab confirms how the query was routed."
    ),
    "rerank": (
        "Shows how Snowflake Cortex reranked the candidate rows. "
        "Each result is listed with the LLM's reasoning for its position."
    ),
    "fetch_sql": (
        "The final SQL executed to fetch full details for the top-ranked "
        "results after reranking."
    ),
    "normalized_request": (
        "The parsed and normalized version of the original user query, "
        "showing extracted fields, detected intent, and the semantic "
        "backend used to process the request."
    ),
}


def _help_caption(key: str) -> None:
    """Render a help caption at the top of a tab."""
    st.caption(f"\u2139\ufe0f {_TAB_HELP.get(key, '')}")


def render_explain_panel(explain: Dict[str, Any]) -> None:
    if not explain:
        return

    response_type = explain.get("_response_type", "order_lookup")
    metric_result = explain.get("_metric_result")

    st.subheader("Explain")

    if response_type == "metric_query":
        _render_metric_explain(explain, metric_result)
    else:
        _render_order_explain(explain)


def _render_metric_explain(explain: Dict[str, Any], metric_result: Dict[str, Any] | None) -> None:
    """Explain view for metric queries routed through the dbt Semantic Layer."""
    tabs = st.tabs([
        "MetricFlow SQL",
        "Candidate SQL",
        "Normalized Request",
    ])

    compiled_sql = ""
    if metric_result and metric_result.get("compiled_sql"):
        compiled_sql = metric_result["compiled_sql"]
    elif explain.get("candidate_sql") and explain["candidate_sql"] != "(metric query via dbt Semantic Layer)":
        compiled_sql = explain["candidate_sql"]

    with tabs[0]:
        _help_caption("metricflow_sql")
        if compiled_sql:
            st.code(compiled_sql, language="sql")

            if metric_result:
                cols = st.columns(2)
                with cols[0]:
                    used = metric_result.get("metrics_used", [])
                    metrics_str = ", ".join(f"`{m}`" for m in used) if used else "\u2014"
                    st.markdown(f"**Metrics:** {metrics_str}")
                with cols[1]:
                    dims = metric_result.get("dimensions_used", [])
                    dims_str = ", ".join(f"`{d}`" for d in dims) if dims else "\u2014"
                    st.markdown(f"**Dimensions:** {dims_str}")
        else:
            st.info("MetricFlow SQL not available for this query.")

    with tabs[1]:
        _help_caption("candidate_sql_metric")
        raw_sql = explain.get("candidate_sql", "")
        if raw_sql and raw_sql != "(metric query via dbt Semantic Layer)":
            st.code(raw_sql, language="sql")
        else:
            st.info("This metric query was executed entirely through the dbt Semantic Layer.")
        row_count = explain.get("candidate_count", "\u2014")
        st.markdown(f"**Rows returned:** {row_count}")

    with tabs[2]:
        _help_caption("normalized_request")
        nr = explain.get("normalized_request")
        if nr:
            st.json(json.dumps(nr, default=str))
        else:
            st.info("No normalized request data available.")

        _render_semantic_info(explain)


def _render_order_explain(explain: Dict[str, Any]) -> None:
    """Explain view for order lookup queries."""
    tabs = st.tabs([
        "Candidate SQL",
        "Rerank",
        "Final Fetch SQL",
        "Normalized Request",
        "Data Health",
        "Data Lineage",
    ])

    qids = explain.get("snowflake_query_ids", {})

    with tabs[0]:
        _help_caption("candidate_sql_order")
        cand_count = explain.get("candidate_count", "\u2014")
        st.markdown(f"**Candidates retrieved:** {cand_count}")
        st.code(explain.get("candidate_sql", ""), language="sql")
        if qids.get("candidate"):
            st.caption(f"Snowflake Query ID: `{qids['candidate']}`")

    with tabs[1]:
        _help_caption("rerank")
        rerank_order = explain.get("rerank_order", [])
        rationale = explain.get("rerank_rationale", {})
        if rerank_order:
            st.markdown("**Reranked order:**")
            for i, oid in enumerate(rerank_order, 1):
                reason = rationale.get(oid, "")
                st.markdown(f"{i}. `{oid}` \u2014 {reason}")
        else:
            st.info("Reranking skipped (exact match or empty candidate set).")

        versions = explain.get("prompt_versions", {})
        if versions:
            parse_ver = versions.get("parse", "\u2014")
            rerank_ver = versions.get("rerank", "\u2014")
            st.caption(
                f"Prompt versions \u2014 parse: `{parse_ver}` "
                f"\u00b7 rerank: `{rerank_ver}`"
            )

        if explain.get("rerank_prompt_used"):
            with st.expander("Raw rerank prompt"):
                st.text(explain["rerank_prompt_used"][:3000])

    with tabs[2]:
        _help_caption("fetch_sql")
        st.code(explain.get("fetch_sql", ""), language="sql")
        if qids.get("fetch_top"):
            st.caption(f"Snowflake Query ID: `{qids['fetch_top']}`")

    with tabs[3]:
        _help_caption("normalized_request")
        nr = explain.get("normalized_request")
        if nr:
            st.json(json.dumps(nr, default=str))
        else:
            st.info("No normalized request data available.")

        _render_semantic_info(explain)

    with tabs[4]:
        _render_data_health_tab(explain)

    with tabs[5]:
        _render_lineage_tab(explain)


def _render_semantic_info(explain: Dict[str, Any]) -> None:
    """Shared section showing semantic backend info."""
    sem_backend = explain.get("semantic_backend")
    sem_objects = explain.get("semantic_objects_used", [])
    if sem_backend:
        st.markdown(f"**Semantic backend:** `{sem_backend}`")
    if sem_objects:
        st.markdown("**Semantic objects used:**")
        for obj in sem_objects:
            st.markdown(f"  - `{obj}`")


def _render_data_health_tab(explain: Dict[str, Any]) -> None:
    """Render model health and source freshness information."""
    health = explain.get("model_health")
    freshness = explain.get("data_freshness")

    if not health and not freshness:
        st.info("Data health information not available (dbt MCP not connected).")
        return

    if health:
        st.markdown("**Model Health \u2014 fct_orders**")
        if isinstance(health, dict):
            status = health.get("status", health.get("state", "unknown"))
            st.markdown(f"Status: `{status}`")

            tests = health.get("tests", health.get("test_results", []))
            if tests:
                st.markdown("**Test Results:**")
                if isinstance(tests, list):
                    for t in tests:
                        if isinstance(t, dict):
                            name = t.get("name", t.get("test_name", "unnamed"))
                            result = t.get("status", t.get("result", "unknown"))
                            icon = "pass" if result.lower() in ("pass", "success") else "fail"
                            st.markdown(f"  - {name}: `{icon}`")
                        else:
                            st.markdown(f"  - {t}")

            # Show any extra keys as raw JSON
            extra = {k: v for k, v in health.items()
                     if k not in ("status", "state", "tests", "test_results")}
            if extra:
                with st.expander("Raw model health"):
                    st.json(json.dumps(extra, default=str))
        else:
            st.json(json.dumps(health, default=str))

    if freshness:
        st.markdown("---")
        st.markdown("**Source Freshness**")
        sources = freshness.get("sources", freshness) if isinstance(freshness, dict) else freshness
        if isinstance(sources, list):
            for src in sources:
                if isinstance(src, dict):
                    name = src.get("name", src.get("source_name", "unknown"))
                    loaded = src.get("loaded_at", src.get("max_loaded_at", ""))
                    freshness_status = src.get("status", src.get("state", ""))
                    line = f"  - **{name}**"
                    if loaded:
                        line += f": last loaded `{loaded}`"
                    if freshness_status:
                        line += f" ({freshness_status})"
                    st.markdown(line)
                else:
                    st.markdown(f"  - {src}")
        else:
            st.json(json.dumps(sources, default=str))


def _render_lineage_tab(explain: Dict[str, Any]) -> None:
    """Render data lineage provenance."""
    lineage = explain.get("lineage")

    if not lineage:
        st.info("Lineage information not available (dbt MCP not connected).")
        return

    st.markdown("**Data Lineage \u2014 fct_orders**")

    # Try to extract a path from common lineage response shapes
    if isinstance(lineage, dict):
        # Look for parent/child relationships or node lists
        parents = lineage.get("parents", lineage.get("upstream", []))
        children = lineage.get("children", lineage.get("downstream", []))

        if parents or children:
            if parents:
                st.markdown("**Upstream (sources):**")
                if isinstance(parents, list):
                    for p in parents:
                        name = p.get("name", p) if isinstance(p, dict) else str(p)
                        st.markdown(f"  - `{name}`")
                else:
                    st.markdown(f"  - `{parents}`")

            st.markdown("**Current model:** `fct_orders` -> `order_search_v`")

            if children:
                st.markdown("**Downstream (consumers):**")
                if isinstance(children, list):
                    for c in children:
                        name = c.get("name", c) if isinstance(c, dict) else str(c)
                        st.markdown(f"  - `{name}`")
                else:
                    st.markdown(f"  - `{children}`")
        else:
            # Render whatever shape we got
            with st.expander("Raw lineage data"):
                st.json(json.dumps(lineage, default=str))
    else:
        st.json(json.dumps(lineage, default=str))
