"""Explain panel — SQL, rerank rationale, semantic objects, MetricFlow SQL."""

import json
import streamlit as st
from typing import Dict, Any


_TAB_HELP = {
    "metricflow_sql": (
        "The SQL generated by dbt MetricFlow from the Semantic Layer. "
        "This query is compiled from governed metric and dimension "
        "definitions — not hand-written — ensuring consistent, auditable results."
    ),
    "candidate_sql_order": (
        "The deterministic SQL query run directly against Snowflake to "
        "retrieve candidate orders matching the search criteria. "
        "This step does not use the Semantic Layer."
    ),
    "candidate_sql_metric": (
        "For metric queries the SQL is generated by dbt MetricFlow "
        "through the Semantic Layer (shown in the MetricFlow SQL tab). "
        "This tab confirms how the query was routed."
    ),
    "rerank": (
        "Shows how Snowflake Cortex reranked the candidate rows. "
        "Each result is listed with the LLM's reasoning for its position."
    ),
    "fetch_sql": (
        "The final SQL executed to fetch full details for the top-ranked "
        "results after reranking."
    ),
    "normalized_request": (
        "The parsed and normalized version of the original user query, "
        "showing extracted fields, detected intent, and the semantic "
        "backend used to process the request."
    ),
}


def _help_caption(key: str) -> None:
    """Render a help caption at the top of a tab."""
    st.caption(f"ℹ️ {_TAB_HELP.get(key, '')}")


def render_explain_panel(explain: Dict[str, Any]) -> None:
    if not explain:
        return

    response_type = explain.get("_response_type", "order_lookup")
    metric_result = explain.get("_metric_result")

    st.subheader("Explain")

    if response_type == "metric_query":
        _render_metric_explain(explain, metric_result)
    else:
        _render_order_explain(explain)


def _render_metric_explain(explain: Dict[str, Any], metric_result: Dict[str, Any] | None) -> None:
    """Explain view for metric queries routed through the dbt Semantic Layer."""
    tabs = st.tabs([
        "MetricFlow SQL",
        "Candidate SQL",
        "Normalized Request",
    ])

    compiled_sql = ""
    if metric_result and metric_result.get("compiled_sql"):
        compiled_sql = metric_result["compiled_sql"]
    elif explain.get("candidate_sql") and explain["candidate_sql"] != "(metric query via dbt Semantic Layer)":
        compiled_sql = explain["candidate_sql"]

    with tabs[0]:
        _help_caption("metricflow_sql")
        if compiled_sql:
            st.code(compiled_sql, language="sql")

            if metric_result:
                cols = st.columns(2)
                with cols[0]:
                    used = metric_result.get("metrics_used", [])
                    st.markdown(f"**Metrics:** {', '.join(f'`{m}`' for m in used) if used else '—'}")
                with cols[1]:
                    dims = metric_result.get("dimensions_used", [])
                    st.markdown(f"**Dimensions:** {', '.join(f'`{d}`' for d in dims) if dims else '—'}")
        else:
            st.info("MetricFlow SQL not available for this query.")

    with tabs[1]:
        _help_caption("candidate_sql_metric")
        raw_sql = explain.get("candidate_sql", "")
        if raw_sql and raw_sql != "(metric query via dbt Semantic Layer)":
            st.code(raw_sql, language="sql")
        else:
            st.info("This metric query was executed entirely through the dbt Semantic Layer.")
        st.markdown(f"**Rows returned:** {explain.get('candidate_count', '—')}")

    with tabs[2]:
        _help_caption("normalized_request")
        nr = explain.get("normalized_request")
        if nr:
            st.json(json.dumps(nr, default=str))
        else:
            st.info("No normalized request data available.")

        _render_semantic_info(explain)


def _render_order_explain(explain: Dict[str, Any]) -> None:
    """Explain view for order lookup queries."""
    tabs = st.tabs([
        "Candidate SQL",
        "Rerank",
        "Final Fetch SQL",
        "Normalized Request",
    ])

    with tabs[0]:
        _help_caption("candidate_sql_order")
        st.markdown(
            f"**Candidates retrieved:** {explain.get('candidate_count', '—')}"
        )
        st.code(explain.get("candidate_sql", ""), language="sql")
        qids = explain.get("snowflake_query_ids", {})
        if qids.get("candidate"):
            st.caption(f"Snowflake Query ID: `{qids['candidate']}`")

    with tabs[1]:
        _help_caption("rerank")
        rerank_order = explain.get("rerank_order", [])
        rationale = explain.get("rerank_rationale", {})
        if rerank_order:
            st.markdown("**Reranked order:**")
            for i, oid in enumerate(rerank_order, 1):
                reason = rationale.get(oid, "")
                st.markdown(f"{i}. `{oid}` — {reason}")
        else:
            st.info("Reranking skipped (exact match or empty candidate set).")

        versions = explain.get("prompt_versions", {})
        if versions:
            st.caption(
                f"Prompt versions — parse: `{versions.get('parse', '—')}` "
                f"· rerank: `{versions.get('rerank', '—')}`"
            )

        if explain.get("rerank_prompt_used"):
            with st.expander("Raw rerank prompt"):
                st.text(explain["rerank_prompt_used"][:3000])

    with tabs[2]:
        _help_caption("fetch_sql")
        st.code(explain.get("fetch_sql", ""), language="sql")
        qids = explain.get("snowflake_query_ids", {})
        if qids.get("fetch_top"):
            st.caption(f"Snowflake Query ID: `{qids['fetch_top']}`")

    with tabs[3]:
        _help_caption("normalized_request")
        nr = explain.get("normalized_request")
        if nr:
            st.json(json.dumps(nr, default=str))
        else:
            st.info("No normalized request data available.")

        _render_semantic_info(explain)


def _render_semantic_info(explain: Dict[str, Any]) -> None:
    """Shared section showing semantic backend info."""
    sem_backend = explain.get("semantic_backend")
    sem_objects = explain.get("semantic_objects_used", [])
    if sem_backend:
        st.markdown(f"**Semantic backend:** `{sem_backend}`")
    if sem_objects:
        st.markdown("**Semantic objects used:**")
        for obj in sem_objects:
            st.markdown(f"  - `{obj}`")
