CREATE OR REPLACE SECRET DEMO_BSC.DBT_CLOUD_TOKEN
  TYPE = GENERIC_STRING
  SECRET_STRING = '${DBT_CLOUD_TOKEN}';

CREATE OR REPLACE NETWORK RULE DEMO_BSC.DBT_CLOUD_RULE
  TYPE = HOST_PORT
  MODE = EGRESS
  VALUE_LIST = ('${DBT_SL_HOST}:443', 'metadata.cloud.getdbt.com:443');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION DBT_CLOUD_EAI
  ALLOWED_NETWORK_RULES = (DEMO_BSC.DBT_CLOUD_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (DEMO_BSC.DBT_CLOUD_TOKEN)
  ENABLED = TRUE;
