CREATE TASK IF NOT EXISTS DEMO_BSC.NIGHTLY_AGENT_EVAL
  WAREHOUSE = DEMO_WH
  SCHEDULE = 'USING CRON 0 4 * * * America/Los_Angeles'
AS CALL DEMO_BSC.RUN_NIGHTLY_EVAL();

CREATE TASK IF NOT EXISTS DEMO_BSC.REFRESH_CATALOG_DAILY
  WAREHOUSE = DEMO_WH
  SCHEDULE = 'USING CRON 0 2 * * * America/Los_Angeles'
AS CALL DEMO_BSC.REFRESH_SEMANTIC_CATALOG();

ALTER TASK DEMO_BSC.NIGHTLY_AGENT_EVAL RESUME;
ALTER TASK DEMO_BSC.REFRESH_CATALOG_DAILY RESUME;
